'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Search,Droplets,Bookmark,History,LayoutGrid,SlidersHorizontal,ArrowUpRight,ArrowRight,Plus,X,ChevronDown,Check,ShieldCheck,FileText,Printer,Download,Upload,Pencil,Trash2,BookOpen,Loader2,AlertCircle,LogOut,Database,ChevronRight} from 'lucide-react';
import {logout} from './login/actions';
import {blank,type Vehicle} from '../lib/catalog';
type View='catalog'|'favorites'|'history'|'manage'|'guide';
type Activity={favorites:string[],history:{id:string,date:string}[]};
const tabs=[{id:'catalog',label:'Buscador',icon:Search},{id:'favorites',label:'Favoritos',icon:Bookmark},{id:'history',label:'Historial',icon:History},{id:'manage',label:'Mi catálogo',icon:Database}] as const;
async function request(path:string,method='GET',data?:unknown){const r=await fetch(path,{method,headers:data?{'Content-Type':'application/json'}:undefined,body:data?JSON.stringify(data):undefined});if(r.status===401){window.location.assign('/login');throw Error('Sesión vencida.');}if(r.status===403){window.location.assign('/activation');throw Error('Licencia pendiente.');}const body=await r.json() as {error?:string,vehicles:Vehicle[],name:string,favorites:string[],history:{id:string,date:string}[]};if(!r.ok)throw Error(body.error||'No se pudo completar la operación.');return body;}
function Modal({children,onClose,label}:{children:ReactNode,onClose:()=>void,label:string}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close();},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-label={label}><button className="close iconbtn" onClick={onClose} aria-label="Cerrar"><X size={20}/></button>{children}</dialog>;}
function CarArt(){return <svg className="car-art" viewBox="0 0 460 160" fill="none" aria-hidden="true"><defs><linearGradient id="paint" x1="210" y1="40" x2="245" y2="145" gradientUnits="userSpaceOnUse"><stop stopColor="#fbfcfd"/><stop offset=".4" stopColor="#c4cbd2"/><stop offset=".72" stopColor="#e6e9eb"/><stop offset="1" stopColor="#7a838c"/></linearGradient><linearGradient id="glass"><stop stopColor="#545b65"/><stop offset="1" stopColor="#202731"/></linearGradient><filter id="blur"><feGaussianBlur stdDeviation="5"/></filter></defs><ellipse cx="235" cy="143" rx="176" ry="7" fill="#afb5ba" opacity=".23" filter="url(#blur)"/><path d="M46 117L52 90Q60 83 112 78L155 40Q169 28 234 30L302 32Q323 34 359 75L402 84Q420 90 423 109L422 128L389 134H70L44 130Z" fill="url(#paint)" stroke="#9aa2aa"/><path d="M127 77L164 45Q174 38 230 39L229 78Z" fill="url(#glass)"/><path d="M238 39L297 41Q309 44 337 77L238 78Z" fill="url(#glass)"/><path d="M240 84V125M125 84L122 125M340 85L352 124M62 91L119 91M391 93L414 99" stroke="#9da5ad"/><path d="M54 95L88 91L83 102L51 105M396 95L416 99L419 107L397 104" fill="#fafbff"/><path d="M49 123H418" stroke="#4e5864" strokeWidth="3"/><path d="M260 89H274M150 89H164" stroke="#727c87" strokeWidth="3" strokeLinecap="round"/><circle cx="106" cy="122" r="25" fill="#23262a"/><circle cx="106" cy="122" r="17" fill="#c0c6cd"/><circle cx="106" cy="122" r="9" fill="#737d89"/><circle cx="366" cy="122" r="25" fill="#23262a"/><circle cx="366" cy="122" r="17" fill="#c0c6cd"/><circle cx="366" cy="122" r="9" fill="#737d89"/><path d="M94 110L118 134M94 134L118 110M354 110L378 134M354 134L378 110" stroke="#edf0f4" strokeWidth="3"/><path d="M32 149H437" stroke="#e2e5e8"/></svg>;}
export default function Workspace(){
 const [view,setView]=useState<View>('catalog'),[vehicles,setVehicles]=useState<Vehicle[]>([]),[activity,setActivity]=useState<Activity>({favorites:[],history:[]}),[name,setName]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[toast,setToast]=useState(''),[search,setSearch]=useState(''),[brand,setBrand]=useState(''),[model,setModel]=useState(''),[year,setYear]=useState(''),[engine,setEngine]=useState(''),[status,setStatus]=useState('all'),[selected,setSelected]=useState<Vehicle|null>(null),[editing,setEditing]=useState<Vehicle|null>(null),[saving,setSaving]=useState(false),[formError,setFormError]=useState('');
 const file=useRef<HTMLInputElement>(null);
 async function load(){setLoading(true);setError('');try{const [c,a]=await Promise.all([request('/api/catalog'),request('/api/activity')]);setVehicles(c.vehicles);setName(c.name);setActivity(a);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(t);},[toast]);
 const documented=vehicles.filter(v=>v.status==='documented').length;
 function reset(){setSearch('');setBrand('');setModel('');setYear('');setEngine('');setStatus('all');}
 const filtered=vehicles.filter(v=>(!brand||v.brand===brand)&&(!model||v.model===model)&&(!year||String(v.year)===year)&&(!engine||v.engine===engine)&&(status==='all'||v.status===status)&&`${v.brand} ${v.model} ${v.engine} ${v.year}`.toLowerCase().includes(search.toLowerCase())&&(view!=='favorites'||activity.favorites.includes(v.id))&&(view!=='history'||activity.history.some(h=>h.id===v.id))).sort((a,b)=>view==='history'?(activity.history.find(h=>h.id===b.id)?.date||'').localeCompare(activity.history.find(h=>h.id===a.id)?.date||''):Number(b.status==='documented')-Number(a.status==='documented'));
 const brands=[...new Set(vehicles.map(v=>v.brand))].sort();
 async function favorite(v:Vehicle){const active=!activity.favorites.includes(v.id);try{await request('/api/activity','PUT',{id:v.id,kind:'favorite',active});setActivity(a=>({...a,favorites:active?[...a.favorites,v.id]:a.favorites.filter(id=>id!==v.id)}));setToast(active?'Ficha guardada en favoritos':'Ficha eliminada de favoritos');}catch(e){setToast((e as Error).message);}}
 async function open(v:Vehicle){setSelected(v);try{await request('/api/activity','PUT',{id:v.id,kind:'history'});setActivity(a=>({...a,history:[{id:v.id,date:new Date().toISOString()},...a.history.filter(h=>h.id!==v.id)]}));}catch(e){setToast((e as Error).message);}}
 async function save(e:React.FormEvent){e.preventDefault();if(!editing)return;setSaving(true);setFormError('');try{await request('/api/catalog','PUT',{...editing,id:editing.id||crypto.randomUUID()});setEditing(null);await load();setToast('Ficha guardada correctamente');}catch(e){setFormError((e as Error).message);}finally{setSaving(false);}}
 async function remove(v:Vehicle){if(!confirm(`¿Eliminar la ficha de ${v.brand} ${v.model} ${v.year} de tu catálogo?`))return;try{await request('/api/catalog','DELETE',{id:v.id});await load();setToast('Ficha eliminada');}catch(e){setToast((e as Error).message);}}
 function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify(vehicles,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='ViscoAr-catalogo.json';a.click();URL.revokeObjectURL(url);setToast('Catálogo exportado');}
 async function importData(f:File){try{if(f.size>1000000)throw Error('El archivo no debe superar 1 MB.');await request('/api/catalog','PUT',JSON.parse(await f.text()));await load();setToast('Catálogo importado');}catch(e){setToast((e as Error).message);}if(file.current)file.current.value='';}
 function startEdit(v:Vehicle){setEditing({...v});setFormError('');}
 function changeView(v:View){setView(v);reset();}
 return <div className="app-shell">
  <aside className="sidebar"><a className="brand" href="/" aria-label="ViscoAr inicio"><span className="brand-icon"><Droplets size={23}/></span>ViscoAr<span className="brand-dot">.</span></a><div className="workspace-label">ESPACIO DE TRABAJO</div><nav>{tabs.map(t=><button key={t.id} onClick={()=>changeView(t.id)} className={view===t.id?'navitem active':'navitem'}><t.icon size={19}/>{t.label}{t.id==='favorites'&&activity.favorites.length>0&&<span className="count">{activity.favorites.length}</span>}</button>)}</nav><div className="sidebar-bottom"><div className="mini-note"><ShieldCheck size={21}/><strong>La fuente hace la diferencia.</strong><p>Cada recomendación, con su respaldo técnico.</p><button onClick={()=>changeView('guide')}>Cómo leer una ficha <ArrowUpRight size={15}/></button></div><button className={view==='guide'?'navitem active':'navitem'} onClick={()=>changeView('guide')}><BookOpen size={19}/>Guía de uso</button><form action={logout}><button className="user" type="submit"><span className="avatar">{(name||'L')[0].toUpperCase()}</span><span><strong>Mi espacio</strong><small>Catálogo privado</small></span><LogOut size={16}/></button></form></div></aside>
  <main><header className="topbar"><span>Mi espacio <ChevronRight size={14}/><strong>{view==='catalog'?'Buscador de lubricación':view==='favorites'?'Favoritos':view==='history'?'Historial':view==='manage'?'Mi catálogo':'Guía de uso'}</strong></span><span className="header-right"><span className="private-badge"><span/>Acceso privado</span><button className="button small" onClick={()=>{setView('manage');startEdit({...blank});}}><Plus size={16}/>Nueva ficha</button></span></header>
  <div className="content">
  {view==='catalog'?<section className="hero"><div className="hero-copy"><span className="eyebrow"><span/>CATÁLOGO DE LUBRICACIÓN</span><h1>El aceite correcto.<br/><span>Sin vueltas.</span></h1><p>Encontrá la viscosidad, capacidad y norma<br className="desktop-break"/> que necesitás. Todo, en una sola ficha.</p><div className="hero-pills"><span><ShieldCheck size={15}/>Fuentes visibles</span><span><Droplets size={15}/>Datos por motor</span></div></div><div className="hero-visual"><span className="visual-caption">PRECISIÓN EN CADA SERVICIO</span><CarArt/><div className="oil-tag"><Droplets size={20}/><div><small>Menos búsquedas.</small><strong>Más claridad.</strong></div></div></div></section>:<div className="page-title"><span className="eyebrow">TU ESPACIO, ORGANIZADO</span><h1>{view==='favorites'?'Siempre a mano.':view==='history'?'Tus últimas consultas.':view==='manage'?'Tu catálogo. Tu control.':'Una ficha. Toda la claridad.'}</h1><p>{view==='favorites'?'Guardá los vehículos que consultás con más frecuencia.':view==='history'?'Retomá una consulta sin empezar de cero.':view==='manage'?'Agregá y actualizá vehículos con su documentación técnica.':'Conocé qué significa cada dato antes de hacer un servicio.'}</p></div>}
  {view==='guide'?<div className="guide-grid">{[['01','Identificá el vehículo','Marca, modelo, año, motor y mercado deben coincidir con el vehículo que vas a atender. Un mismo modelo puede tener distintas especificaciones.'],['02','Leé la especificación','La viscosidad SAE (por ejemplo, 5W-30) describe el comportamiento del aceite. La homologación del fabricante es un requisito adicional: no alcanza con igualar la viscosidad.'],['03','Revisá la capacidad','La ficha indica litros con cambio de filtro. Ajustá el nivel según el procedimiento del manual y verificá la varilla o el sistema de medición del vehículo.'],['04','Consultá la fuente','Una ficha documentada incluye el enlace y las páginas del documento. Este estado indica que se cargó una referencia; no implica una certificación automática.'],['05','Gestioná tu catálogo','En Mi catálogo podés crear, editar y eliminar fichas. Exportá un JSON como respaldo e importá el mismo formato, hasta 200 fichas por lote. La importación actualiza por ID.'],['06','Imprimí y compartí','Abrí una ficha y usá Imprimir / PDF. En el diálogo de tu dispositivo podés guardarla como PDF. Las fichas pendientes ocultan recomendaciones.']].map(([n,t,p])=><article className="guide-card" key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div>:<>
  <section className="search-panel"><div className="panel-heading"><div><Search size={19}/><h2>{view==='manage'?'Buscar en mi catálogo':'Encontrá tu vehículo'}</h2></div><button className="textbtn" onClick={reset}>Limpiar filtros</button></div><div className="search-input"><Search size={20}/><input aria-label="Buscar vehículo" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscá una marca, modelo o motor…"/><kbd>Buscar</kbd></div><div className="selectors">{[{label:'Marca',value:brand,options:brands,change:(v:string)=>{setBrand(v);setModel('');setYear('');setEngine('');}},{label:'Modelo',value:model,options:[...new Set(vehicles.filter(v=>!brand||v.brand===brand).map(v=>v.model))].sort(),change:(v:string)=>{setModel(v);setYear('');setEngine('');}},{label:'Año',value:year,options:[...new Set(vehicles.filter(v=>(!brand||v.brand===brand)&&(!model||v.model===model)).map(v=>String(v.year)))].sort().reverse(),change:(v:string)=>{setYear(v);setEngine('');}},{label:'Motor',value:engine,options:[...new Set(vehicles.filter(v=>(!brand||v.brand===brand)&&(!model||v.model===model)&&(!year||String(v.year)===year)).map(v=>v.engine))].sort(),change:setEngine}].map(f=><label key={f.label}><span>{f.label}</span><div><select value={f.value} onChange={e=>f.change(e.target.value)} aria-label={f.label}><option value="">{f.label==='Marca'?'Todas las marcas':f.label==='Modelo'?'Todos los modelos':f.label==='Año'?'Todos los años':'Todos los motores'}</option>{f.options.map(o=><option key={o}>{o}</option>)}</select><ChevronDown size={15}/></div></label>)}</div></section>
  <div className="results-top"><div><h2>{view==='favorites'?'Fichas favoritas':view==='history'?'Consultas recientes':view==='manage'?'Fichas del catálogo':'Explorá el catálogo'}</h2><span>{loading?'Cargando…':`${filtered.length} ${filtered.length===1?'vehículo':'vehículos'}`}</span></div><div className="result-actions">{view==='manage'?<><button className="button secondary small" onClick={exportData} disabled={loading}><Download size={15}/>Exportar</button><button className="button secondary small" onClick={()=>file.current?.click()} disabled={loading}><Upload size={15}/>Importar</button><input ref={file} type="file" accept=".json,application/json" hidden onChange={e=>{if(e.target.files?.[0])void importData(e.target.files[0]);}}/></>:view==='history'?<button className="textbtn" onClick={async()=>{if(!confirm('¿Vaciar el historial de consultas?'))return;try{await request('/api/activity','DELETE');setActivity(a=>({...a,history:[]}));}catch(e){setToast((e as Error).message);}}}>Vaciar historial</button>:<><SlidersHorizontal size={16}/><select aria-label="Estado de documentación" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">Todos los estados</option><option value="documented">Documentadas</option><option value="pending">Pendientes</option></select></>}</div></div>
  {error?<div className="empty"><AlertCircle/><h3>No pudimos cargar tu catálogo</h3><p>{error}</p><button className="button" onClick={load}>Reintentar</button></div>:loading?<div className="loading"><Loader2 className="spin"/>Cargando tu espacio…</div>:!filtered.length?<div className="empty"><Search size={30}/><h3>{view==='favorites'?'Tus favoritos empiezan acá':view==='history'?'Todavía no hay consultas':'No encontramos coincidencias'}</h3><p>{view==='favorites'?'Tocá el marcador de una ficha para guardarla.':view==='history'?'Abrí una ficha y aparecerá en este espacio.':'Probá con otro filtro o agregá el vehículo a tu catálogo.'}</p><button className="button secondary" onClick={()=>changeView('catalog')}>Volver al buscador</button></div>:view==='manage'?<div className="table-wrap"><table><thead><tr><th>Vehículo</th><th>Motor / año</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{filtered.map(v=><tr key={v.id}><td><strong>{v.brand} {v.model}</strong><small>{v.market}</small></td><td>{v.engine}<small>{v.year} · {v.fuel}</small></td><td><span className={`badge ${v.status}`}>{v.status==='documented'?'Documentada':'Pendiente'}</span></td><td><div className="table-actions"><button className="iconbtn" onClick={()=>open(v)} aria-label={`Ver ${v.model}`}><FileText size={17}/></button><button className="iconbtn" onClick={()=>startEdit(v)} aria-label={`Editar ${v.model}`}><Pencil size={17}/></button><button className="iconbtn" onClick={()=>remove(v)} aria-label={`Eliminar ${v.model}`}><Trash2 size={17}/></button></div></td></tr>)}</tbody></table></div>:<div className="vehicle-grid">{filtered.map(v=><article className="vehicle-card" key={v.id}><div className="card-top"><span className={`badge ${v.status}`}>{v.status==='documented'?<ShieldCheck size={13}/>:<FileText size={13}/>} {v.status==='documented'?'Documentada':'Pendiente de fuente'}</span><button className={`iconbtn bookmark ${activity.favorites.includes(v.id)?'saved':''}`} onClick={()=>favorite(v)} aria-label={activity.favorites.includes(v.id)?`Quitar ${v.model} de favoritos`:`Guardar ${v.model}`}><Bookmark size={19}/></button></div><div className="vehicle-name"><small>{v.brand.toUpperCase()}</small><h3>{v.model}</h3><p>{v.engine} <span>·</span> {v.year}</p></div><div className="card-data">{v.status==='documented'?<><div><small>VISCOSIDAD SAE</small><strong>{v.viscosity}</strong></div><div><small>CON FILTRO</small><strong>{v.capacity} <em>L</em></strong></div></>:<p><FileText size={18}/>Información técnica por documentar</p>}</div><div className="card-bottom"><span>{v.market} <span>·</span> {v.fuel}</span><button onClick={()=>open(v)}>Ver ficha <ArrowUpRight size={17}/></button></div></article>)}</div>}
  <section className="catalog-note"><span className="note-icon"><ShieldCheck size={22}/></span><div><strong>Información clara. Fuentes a la vista.</strong><p>{documented} ficha{documented===1?'':'s'} documentada{documented===1?'':'s'} y {vehicles.length-documented} pendiente{vehicles.length-documented===1?'':'s'}. El catálogo inicial está en construcción.</p></div><button className="textbtn" onClick={()=>changeView('guide')}>Conocé el criterio <ArrowRight size={16}/></button></section>
  </>}
  <footer><span>ViscoAr. <span>Precisión para tu próximo servicio.</span></span><span>Hecho para talleres y lubricentros</span></footer>
  </div></main>
  {toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
  {selected&&<Modal onClose={()=>setSelected(null)} label={`Ficha ${selected.brand} ${selected.model}`}><div className="detail"><span className={`badge ${selected.status}`}>{selected.status==='documented'?'Ficha documentada':'Pendiente de documentación'}</span><span className="eyebrow">{selected.brand} · {selected.market}</span><h2>{selected.model}</h2><p className="detail-sub">{selected.engine} · {selected.year} · {selected.fuel}</p>{selected.status==='documented'?<><div className="detail-oil"><div><Droplets size={24}/><small>VISCOSIDAD SAE</small><strong>{selected.viscosity}</strong></div><div><small>CAPACIDAD CON FILTRO</small><strong>{selected.capacity} <em>L</em></strong></div></div><dl><div><dt>Especificación / homologación</dt><dd>{selected.specification}</dd></div><div><dt>Filtro de aceite</dt><dd>{selected.filter||'Sin referencia documentada'}</dd></div><div><dt>Refrigerante</dt><dd>{selected.coolant||'Sin datos documentados'}</dd></div><div><dt>Transmisión</dt><dd>{selected.transmission||'Sin datos documentados'}</dd></div></dl><a className="source-link" href={selected.source} target="_blank" rel="noopener noreferrer"><FileText size={20}/><span><strong>Consultar documento fuente</strong><small>Páginas {selected.sourcePage}</small></span><ArrowUpRight size={18}/></a></>:<div className="pending-info"><FileText size={28}/><h3>Esta ficha todavía no recomienda aceite.</h3><p>Completá los datos y la fuente desde Mi catálogo para documentar esta aplicación.</p></div>}<div className="detail-notes"><strong>Notas de aplicación</strong><p>{selected.notes||'Sin notas adicionales.'}</p><small>Última actualización: {selected.updated||'—'}</small></div><div className="detail-actions"><button className="button" onClick={()=>window.print()}><Printer size={17}/>Imprimir / PDF</button><button className="button secondary" onClick={()=>favorite(selected)}><Bookmark size={17}/>{activity.favorites.includes(selected.id)?'Guardada':'Guardar'}</button><button className="button secondary" onClick={()=>{const v=selected;setSelected(null);startEdit(v);setView('manage');}}><Pencil size={17}/>Editar</button></div><div className="print-brand">ViscoAr. · Ficha de lubricación · {new Date().toLocaleDateString('es-AR')}</div></div></Modal>}
  {editing&&<Modal onClose={()=>{if(!saving)setEditing(null);}} label="Editor de ficha"><form className="editor" onSubmit={save}><span className="eyebrow">MI CATÁLOGO</span><h2>{editing.id?'Editar ficha':'Nueva ficha'}</h2><p>Definí la aplicación exacta y adjuntá su fuente técnica.</p><div className="form-grid">{(['brand','model','year','engine','market','viscosity','capacity','specification','filter','coolant','transmission','source','sourcePage'] as const).map(key=><label className={['source','specification','transmission'].includes(key)?'wide':''} key={key}><span>{{brand:'Marca',model:'Modelo',year:'Año',engine:'Motor / versión',market:'Mercado',viscosity:'Viscosidad SAE',capacity:'Litros con filtro',specification:'Especificación / homologación',filter:'Referencia filtro de aceite',coolant:'Refrigerante',transmission:'Transmisión',source:'URL del documento (HTTPS)',sourcePage:'Páginas de referencia'}[key]}</span><input value={editing[key]} type={key==='year'?'number':key==='source'?'url':'text'} min={key==='year'?1950:undefined} max={key==='year'?2030:undefined} required={['brand','model','year','engine','market'].includes(key)||editing.status==='documented'&&['source','sourcePage','viscosity','capacity','specification'].includes(key)} onChange={e=>setEditing({...editing,[key]:key==='year'?Number(e.target.value):e.target.value})}/></label>)}<label><span>Combustible</span><select value={editing.fuel} onChange={e=>setEditing({...editing,fuel:e.target.value as Vehicle['fuel']})}>{['Nafta','Diésel','Híbrido'].map(s=><option key={s}>{s}</option>)}</select></label><label><span>Estado de la ficha</span><select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as Vehicle['status']})}><option value="pending">Pendiente</option><option value="documented">Documentada</option></select></label><label className="wide"><span>Notas de aplicación</span><textarea rows={3} value={editing.notes} onChange={e=>setEditing({...editing,notes:e.target.value})}/></label></div><p className="form-help">Para documentar una ficha, completá viscosidad, capacidad, homologación, enlace y páginas. Verificá que la fuente corresponda a este motor y mercado.</p>{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={()=>setEditing(null)} disabled={saving}>Cancelar</button><button className="button" disabled={saving}>{saving?<Loader2 size={17} className="spin"/>:<Check size={17}/>}Guardar ficha</button></div></form></Modal>}
 </div>;
}
