import { z } from 'zod';
export const vehicleSchema = z.object({
 id:z.string().min(1).max(100),brand:z.string().trim().min(1).max(80),model:z.string().trim().min(1).max(100),year:z.number().int().min(1950).max(2030),engine:z.string().trim().min(1).max(100),fuel:z.enum(['Nafta','Diésel','Híbrido']),market:z.string().trim().min(1).max(100),viscosity:z.string().trim().max(60),capacity:z.string().trim().max(40),specification:z.string().trim().max(200),filter:z.string().trim().max(100),coolant:z.string().trim().max(200),transmission:z.string().trim().max(200),source:z.string().max(2000).refine(v=>v===''||/^https:\/\//i.test(v),'La fuente debe ser HTTPS.'),sourcePage:z.string().trim().max(120),notes:z.string().trim().max(2000),status:z.enum(['documented','pending']),updated:z.string().max(30)
}).superRefine((v,c)=>{if(v.status==='documented'&&(!v.source||!v.sourcePage||!v.viscosity||!v.capacity||!v.specification))c.addIssue({code:'custom',message:'Una ficha documentada requiere viscosidad, capacidad, norma, fuente y páginas.'});});
export type Vehicle=z.infer<typeof vehicleSchema>;
export const blank:Vehicle={id:'',brand:'',model:'',year:2026,engine:'',fuel:'Nafta',market:'Argentina',viscosity:'',capacity:'',specification:'',filter:'',coolant:'',transmission:'',source:'',sourcePage:'',notes:'',status:'pending',updated:''};
export const seed:Vehicle[]=[{...blank,id:'ford-fiesta-2019-16',brand:'Ford',model:'Fiesta',year:2019,engine:'1.6 Ti-VCT Sigma',viscosity:'5W-30',capacity:'4',specification:'Ford WSS-M2C913-D',coolant:'5,5 L · Ford WSS-M97B44-D',transmission:'Manual: 2,1 L · SAE 75W · WSS-M2C200-D2',source:'https://www.ford.com.ar/content/dam/Ford/website-assets/latam/ar/posventa/mantenimientos%20programados/nuevo-fiesta/far-nuevo-fiesta-manual-propietario-abril-2019.pdf',sourcePage:'203 y 209–210 (PDF: 205 y 211–212)',notes:'Capacidad con cambio de filtro. Sin filtro: 3,7 L. Aplicación según manual de Ford Argentina, edición abril de 2019. Confirmar versión y motor antes de usar la ficha.',status:'documented',updated:'2026-10-04'},...[['Toyota','Hilux',2020,'2.8 turbodiésel','Diésel'],['Volkswagen','Amarok',2020,'2.0 TDI','Diésel'],['Chevrolet','Onix',2021,'1.0 turbo','Nafta'],['Fiat','Cronos',2022,'1.3 Firefly','Nafta'],['Renault','Kangoo',2020,'1.6 SCe','Nafta'],['Peugeot','208',2022,'1.6 VTi','Nafta']].map((v,i)=>({...blank,id:'pending-'+i,brand:v[0] as string,model:v[1] as string,year:v[2] as number,engine:v[3] as string,fuel:v[4] as Vehicle['fuel'],notes:'Ficha inicial pendiente de documentación técnica. No se muestran recomendaciones hasta completar su fuente.',updated:'2026-10-04'}))];

const rangerSource='https://www.ford.com.ar/content/dam/Ford/website-assets/latam/ar/posventa/mantenimientos%20programados/ranger/far-ranger-manual-propietario-abril-2019.pdf';
for(const [engine,capacity,fuel,coolant] of [['2.2 Duratorq-TDCi','8,6','Diésel','11,5 L'],['3.2 Duratorq-TDCi','9,8','Diésel','MT82: 12,9 L'],['2.5 Duratec','6,4','Nafta','11 L']]) seed.push({...blank,id:'ford-ranger-2019-'+engine.slice(0,3),brand:'Ford',model:'Ranger',year:2019,engine,fuel:fuel as Vehicle['fuel'],viscosity:'5W-30',capacity,specification:'Ford WSS-M2C913-D',coolant:coolant+' · WSS-M97B44-D',transmission:'MT82: 2,7 L · WSS-M2C200-D2; MT75: 1,7 L · WSD-M2C200-C. Confirmar caja.',source:rangerSource,sourcePage:'301–302 (PDF: 303–304)',status:'documented',notes:'Manual Argentina, edición abril de 2019, vehículos fabricados desde 15/04/2019. Capacidad con cambio de filtro. Confirmar fecha de fabricación, motor y transmisión; no extender esta ficha a otros años o generaciones.',updated:'2026-10-04'});
